// BLB
export const REQUEST_LEAGUES = "REQUEST_LEAGUES";
export const RECEIVE_LEAGUES = "RECEIVE_LEAGUES";
export const ADD_LEAGUE = "ADD_LEAGUE";

// FG
export const REQUEST_FG_SEASONS = "REQUEST_FG_SEASONS";
export const RECEIVE_FG_SEASONS = "RECEIVE_FG_SEASONS";
